services:
  - type: web
    name: transpacharity-api
    env: go
    buildCommand: ./render-build.sh
    startCommand: cd backend && ./transpacharity-api
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DB_SSL_MODE
        value: require
      - key: DATABASE_URL
        fromDatabase:
          name: transpacharity-db
          property: connectionString

  - type: web
    name: transpacharity-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://transpacharity-api.onrender.com/api

databases:
  - name: transpacharity-db
    plan: starter